name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile Passwdgen.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Password-Generator-EXE
          path: dist/Passwdgen.exe
