name: Build and Commit EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # nécessaire pour git push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: python -m PyInstaller --onefile passwdgenwind.py

      - name: Prepare output directory
        shell: cmd
        run: |
          if exist build_output rmdir /s /q build_output
          mkdir build_output
          copy dist\passwdgenwind.exe build_output\passwdgenwind.exe


      - name: Commit EXE back to repo
        if: github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add build_output/passwdgenwind.exe
          git diff --cached --quiet || git commit -m "Add built executable [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
